name: Quality

on:
  push:
    branches:
      - main
  pull_request:
  # every Sunday at midnight
  schedule:
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

  slack:
    name: Slack
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Send Slack message
        uses: lazy-actions/slatify@v3.0.0
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':snake: Quality'
          url: ${{ secrets.SLACK_WEBHOOK }}
